### PR TITLE
fix: Animal Kingdom results showing up in App.co

### PR DESCRIPTION
**Pull request by kyranjamie**
Not sure if this is the best way to filter the query, but this should filter out most the animal kingdom submissions.

See there was an issue https://github.com/blockstack/app.co/issues/386 before relating to this, but results are still showing up on app.co.

### CODE REVIEW

**Comment by kyranjamie** [comment]
As discussed earlier with Hank, the top Animal Kingdom entries (we don't want to see), so this PR can be closed.

**Comment by moxiegirl** [comment]
@kyranjamie What is "removed on the FE" --- the acronym means nothing to me.

**Comment by kyranjamie** [comment]
Rephrased: the top "Animal Kingdom" results we don't want to see, should be hidden via the frontend, not filtered out of the db query.

Though, it sounds like there is mixed opinion on whether these should be hidden at all.

**Comment by moxiegirl** [comment]
@kyranjamie You didn't say but it appears "FE" means "frontend" to you. It meant Forward Engineer at Palantir.  

We actually added the Sample Blockstack App category so people can see the interface --- not just as a support for Animal Kingdom. I'll need to see the results of the db query to determine if this is useful to me. My assumption is the team does intend to continue to support this example as it is key in many Growth campaigns.

**Comment by kyranjamie** [comment]
When making this PR, I didn't realise there was a sample app category, so apologies for the confusion.

As I now understand, the only place we want to hide the animal kingdom results is the _Popular Decentralized Apps_ section of the homepage.

**Pull request closed without merging**
